steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/check-1:$COMMIT_SHA",'--build-arg=ENV=$_PORT', "."]
    env:
      - "MONGO_DB_URI=${_MONGO_DB_URI}"
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/check-1:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "check-1-service",
        "--image",
        "gcr.io/$PROJECT_ID/check-1:$COMMIT_SHA",
        "--region",
        "asia-south1",
      ]
images:
  - gcr.io/$PROJECT_ID/check-1:$COMMIT_SHA
